_target_: src.models.hyperspectral_classification.HyperspectralLitModule

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.1 
  weight_decay: 0.09

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.HSI_CNN.HSICNN
  n_bands: ${data.n_bands}
  n_classes: ${data.n_classes}
  patch_size: 3
  n_planes: 90

# compile model for faster training with pytorch 2.0
compile: false