_target_: src.models.hyperspectral_classification.HyperspectralLitModule

optimizer:
  _target_: torch.optim.Adagrad
  _partial_: true
  lr: 0.01
  weight_decay: 0.01

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.MultiScale_CNN.MultiScaleCNN
  n_bands: ${data.n_bands}
  n_classes: ${data.n_classes}
  patch_size: 7

# compile model for faster training with pytorch 2.0
compile: false