defaults:
  - _self_
  - data: indian_pines
  - model: multiscale_cnn
  - logger: wandb
  - trainer: default
  - paths: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: /Users/abigail/Documents/projects/Hyperspectral-Zoo/logs/train/runs/2024-11-22_21-40-27/checkpoints/last.ckpt