defaults: 
  - _self_
  - data: indian_pines
  - model: cnn_1d
  - callbacks: none 
  - logger: wandb 
  - trainer: default 
  - paths: default 
  - hydra: default 
  - debug: null 

# other configs 
task_name: "train"
train: True 
test: True # eval on test set using best model weights from training 
ckpt_path: null