# default debugging, runs 1 full epoch
# other debugging configs can inherit from this one

# overwrite so debug logs are stored in debug folder
task_name: "debug"

# disable loggers 
logger: null

# sets level of all command line loggers to 'DEBUG'
# https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
hydra:
  job_logging:
    root:
      level: DEBUG

trainer:
  max_epochs: 1
  accelerator: cpu 
  devices: 1 
  detect_anomaly: true 

data:
  num_workers: 0
  pin_memory: False